services:
  local-mysql:
    image: mysql
    container_name: techup-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shopping
    ports:
      - "3307:3306"
    platform: linux/arm64
